# 不在k8s中启动的话，在discovery和processors中加入Host: ${Node}
filebeat.config.prospectors:
  enabled: true
  path: prospectors.d/*.yml
  reload: 
    enabled: true
    period: 5s

filebeat.discovery:
  kubernetes:
    namespace: ${K8S_NAMESPACE}
    api_server: ${K8S_APISERVER}
    sync_period: 1m

processors:
- add_kubernetes_metadata:
    namespace: ${K8S_NAMESPACE}
    api_server: ${K8S_APISERVER}
    sync_period: 1m

fields_under_root: true
fields:
  kubernetes:
    cluster: 
      name: ${K8S_CLUSTER}
logging.level: ${FB_LOGLEVEL}
output.elasticsearch:
  hosts: ['${ES_HOST}:${ES_PORT}']
