filebeat.config.prospectors:
  enabled: true
  path: prospectors.d/*.yml
  reload: 
    enabled: true
    period: 5s

filebeat.discovery:
  kubernetes:
    namespace: ${NAMESPACE}
    host: ${NODE}
    api_server: ${APISERVER}
    sync_period: 1m

processors:
- add_kubernetes_metadata:
    namespace: ${NAMESPACE}
    host: ${NODE}
    api_server: ${APISERVER}
    sync_period: 1m

fields_under_root: true
fields:
  kubernetes:
    cluster: 
      name: ${CLUSTER}
    node: 
      name: ${NODE}

output.elasticsearch:
  hosts: ['${ES_HOST}']
