# 不在k8s中启动的话，在discovery和processors中加入Host: ${Node}
metricbeat.config.modules:
  enabled: true
  path: modules.d/*.yml
  reload: 
    enabled: true
    period: 5s

metricbeat.discovery:
  kubernetes:
    namespace: ${K8S_NAMESPACE}
    api_server: ${K8S_APISERVER}
    sync_period: ${BEAT_DISCOVERY_PERIOD}

processors:
- add_kubernetes_metadata:
    namespace: ${K8S_NAMESPACE}
    api_server: ${K8S_APISERVER}
    sync_period: ${K8S_SYNC_PERIOD}

fields_under_root: true
fields:
  kubernetes:
    cluster: 
      name: ${K8S_CLUSTER}
logging.level: ${MB_LOGLEVEL}
setup.template.name: "metricbeat-${K8S_CLUSTER}"        #顶格，和output对其
setup.template.pattern: "metricbeat-${K8S_CLUSTER}-*"   #顶格，和output对其
output.elasticsearch:
  hosts: ['${ES_HOST}:${ES_PORT}']
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}
  protocal: ${ES_PROTOCOL}
  index: "metricbeat-${K8S_CLUSTER}-%{+yyyy.MM.dd}"

