# 不在k8s中启动的话，在discovery和processors中加入Host: ${Node}
metricbeat.config.modules:
  enabled: true
  path: modules.d/*.yml
  reload: 
    enabled: true
    period: 5s

metricbeat.discovery:
  kubernetes:
    namespace: ${NAMESPACE}
    api_server: ${APISERVER}
    sync_period: 1m

processors:
- add_kubernetes_metadata:
    namespace: ${NAMESPACE}
    api_server: ${APISERVER}
    sync_period: 1m

fields_under_root: true
fields:
  kubernetes:
    cluster: 
      name: ${CLUSTER}

output.elasticsearch:
  hosts: ['${ES_HOST}']

