metricbeat.config.modules:
  enabled: true
  path: modules.d/*.yml
  reload: 
    enabled: true
    period: 5s

metricbeat.discovery:
  kubernetes:
    namespace: ${NAMESPACE}
    host: ${NODE}
    api_server: ${APISERVER}
    sync_period: 1m

processors:
- add_kubernetes_metadata:
    namespace: ${NAMESPACE}
    host: ${NODE}
    api_server: ${APISERVER}
    sync_period: 1m

fields_under_root: true
fields:
  kubernetes:
    cluster: 
      name: ${CLUSTER}
    node: 
      name: ${NODE}

output.elasticsearch:
  hosts: ['10.203.40.99:9200']

